### PR TITLE
Add Linux support

### PR DESCRIPTION
**Pull request by Seb-Ltz**
# Add Linux Support

## :recycle: Current situation & Problem

Currently when trying to build this repository for Linux, the build fails. As this module is central to the Spezi Framework, this limits the possibility of having Spezi modules working on Linux, limiting the ability to create server side applications.

## :gear: Release Notes
* Swift Build succeeds on Linux
  * Localizations have been removed when building on Linux
  * Functions using Objective-C, as well as Objective-C code has been disabled when building on Linux
* Addition of a Dockerfile to test the Swift build on a Linux environment locally
* Addition of GitHub action to test the successful build and tests

## :books: Documentation
* Comments have been added where relevant

## :white_check_mark: Testing
* Tests are working on Linux
  * All tests that are expected to be run on linux have been migrated to Swift Testing
  * Tests requiring to be run on a Darwin architecture have been disabled on Linux (such as tests requiring Objective-C)

## 🏗️ Current Work Left To Do
- [X] ~~The Dockerfile seems to hang when running `swift test` with XCTests, while working when running fine with `swift test --disable-xctest`. To fix this, a solution could be to migrate the rest of the tests to Swift Testing.~~
- [X] ~~For some tests to work on Linux, they have simply been marked with `@preconcurrency` attribute, this may need some refactoring / that attribute will probably be removed during migration to Swift Testing~~ 
- [ ] `RecursiveRWLock` is using types such as `pthread_t` or `pthread_rwlock_t`, which are types only available on Darwin architectures, thus this class is currently unaccessible on Linux.
- [ ] After feedback on the GitHub action, we may move the action into [Spezi's .github](https://github.com/StanfordSpezi/.github) repository 
## :pencil: Code of Conduct & Contributing Guidelines
By creating and submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [X] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: .github/workflows/linux-build-test.yml
Comment (PSchmiedmayer) [inline .github/workflows/linux-build-test.yml:1]: Nice setup here! I agree with the PR description; if we keep this, we should rename this to `swift-build-and-test` and eventually move it to https://github.com/StanfordBDHG/.github once we have finished the major work on this PR.

There is also a reusable workflow in the main Swift Repo that we might want to explore using: [https://github.com/swiftlang/github-workflows/.github/workflows/swift_package_test.yml](https://github.com/swiftlang/github-workflows/blob/937e1789749e691f4c10719078efb65f7648c5a3/.github/workflows/swift_package_test.yml). Would also even add the possibility to check windows builds in the future.

File: .github/workflows/test-linux-build.yml
Comment (PSchmiedmayer) [inline .github/workflows/test-linux-build.yml:1]: Probably can be removed?

File: Sources/SpeziFoundation/Concurrency/RecursiveRWLock.swift
Comment (PSchmiedmayer) [inline Sources/SpeziFoundation/Concurrency/RecursiveRWLock.swift:1]: @bauer-andreas Wondering if there is a way to also make this available on Linux?

File: Sources/SpeziFoundation/Misc/TimeoutError.swift [hunk 1]
```diff
@@ -18,11 +18,24 @@ public struct TimeoutError {
...
+        )
+    #endif
     }
 
     public var failureReason: String? {
+    #if os(Linux)
+        return "The operation timed out."
+    #else
         String(localized: LocalizedStringResource("The operation timed out.", bundle: .atURL(Bundle.module.bundleURL)))
+    #endif
```
Comment (PSchmiedmayer) [inline Sources/SpeziFoundation/Misc/TimeoutError.swift:38]: I think we can import the open-source version of foundation for Linux Builds and then use sting localization. The implementation seems to support it: https://swiftpackageindex.com/swiftlang/swift-foundation; wondering if an explicit import of Foundation would fix this?

File: Tests/SpeziFoundationTests/AsyncSemaphoreTests.swift
Comment (PSchmiedmayer) [inline Tests/SpeziFoundationTests/AsyncSemaphoreTests.swift:1]: @bauer-andreas Would be great if you can double-check all the changes here.

File: Tests/SpeziFoundationTests/ExceptionHandlingTests.swift [hunk 2]
```diff
@@ -10,6 +10,7 @@
 import SpeziFoundation
 import XCTest
 
+#if !os(Linux) // Objective C not supported in Linux, since there is no Objective C runtime
```
Comment (PSchmiedmayer) [inline Tests/SpeziFoundationTests/ExceptionHandlingTests.swift:13]: Similar comment as noted above:
```suggestion
#if canImport(ObjectiveC)
```

File: Sources/SpeziFoundation/Misc/ObjCExceptionHandling.swift [hunk 3]
```diff
@@ -7,6 +7,7 @@
 //
 
 import Foundation
+#if !os(Linux) // Objective C not supported in Linux, since there is no Objective C runtime
```
Comment (PSchmiedmayer) [inline Sources/SpeziFoundation/Misc/ObjCExceptionHandling.swift:10]:
```suggestion
#if canImport(ObjectiveC)
```

File: Tests/SpeziFoundationTests/MainActorExecutionTests.swift
Comment (PSchmiedmayer) [inline Tests/SpeziFoundationTests/MainActorExecutionTests.swift:1]: @bauer-andreas Good to also have a safety check on this.

File: Tests/SpeziFoundationTests/RWLockTests.swift [hunk 4]
```diff
@@ -9,7 +9,7 @@
 import SpeziFoundation
 import XCTest
 
-
+#if !os(Linux)
```
Comment (PSchmiedmayer) [inline Tests/SpeziFoundationTests/RWLockTests.swift:12]: TODO to remove this once we resolved the Linux compilation elements.

File: Tests/SpeziFoundationTests/RuntimeEnvironmentTests.swift [hunk 5]
```diff
@@ -23,7 +22,7 @@ struct RuntimeEnvironmentTests {
         #endif
     }
     
-    @Test
+    @Test(.disabled(if: isLinux, "Skipped on Linux: runningInXCTest() calls NSClassFromString() which uses the Objective-C runtime."))
```
Comment (PSchmiedmayer) [inline Tests/SpeziFoundationTests/RuntimeEnvironmentTests.swift:25]: Can we add an availability annotation to the implementation to avoid that it can even be called on other platforms than apple ones? We might even want to deprecate it @bauer-andreas?

File: Tests/SpeziFoundationTests/TestUtils.swift [hunk 6]
```diff
@@ -0,0 +1,16 @@
...
+//
+
+
+var isLinux: Bool {
+#if os(Linux)
+    return true
+#else
+    return false
+#endif
+}
```
Comment (PSchmiedmayer) [inline Tests/SpeziFoundationTests/TestUtils.swift:16]: Wondering if we need this; not sure if this was referenced somewhere.

**Review by PSchmiedmayer — COMMENTED** [review]
Great job, thank you for all the improvements here @Seb-Ltz!

I had a few comments and would be great to get input from @bauer-andreas and @lukaskollmer before we merge the PR.

File: Tests/SpeziFoundationTests/TestUtils.swift (hunk 6 above)
Comment (Seb-Ltz) [reply Tests/SpeziFoundationTests/TestUtils.swift]: It was previously referenced twice for disabling incompatible tests on Linux:
```swift
@Test(.disabled(if: isLinux))
```

However, one of those references involved a test (`RuntimeEnvironmentTests.swift`) with `ProcessInfo.isRunningInXCTest` which has now an `@available(*, unavailable)` notation for Linux, causing a compilation error when that test was compiled for Linux.

I replaced that test with
```swift
#if !os(Linux)
@Test
func runningInXCTest() {
    #expect(ProcessInfo.isRunningInXCTest)
}
#else
@Test(.disabled("Skipped on Linux: runningInXCTest() calls NSClassFromString() which uses the Objective-C runtime."))
func runningInXCTest() { }
#endif
```

Since the var was then only referenced once, I removed the `isLinux` variable and its file. I then used a similar approach to remove that second occurrence in `RuntimeEnvironmentTests.swift` where I directly disabled the test using `#if os(Linux)` compilation directives instead of relying on `isLinux`.

File: .github/workflows/linux-build-test.yml
Comment (Seb-Ltz) [reply .github/workflows/linux-build-test.yml:1]: Workflow has been renamed for now.

And thank you for the reference to the `swift_package_test.yml` workflow. Should we consider adopting that workflow and use a matrix approach to test our code against multiple Swift versions on Linux? Or should we only use the latest version of Swift? I’m open to either approach, though at the moment, the code only compiles with Swift 6.1, so we may be limited for now.

Also, since their `swift_version` matrix doesn’t include the most recent stable versions, we would likely need to maintain our own version of the workflow if we go that route.

File: Tests/SpeziFoundationTests/AsyncSemaphoreTests.swift [hunk 7]
```diff
@@ -61,129 +63,149 @@ final class AsyncSemaphoreTests: XCTestCase {   // swiftlint:disable:this type_b
...
+            task.cancel()
+            await task.value
         }
-        task.cancel()
-        wait(for: [exp], timeout: 5)
     }
-    
+
+
+    @Test()
```
Comment (lukaskollmer) [inline Tests/SpeziFoundationTests/AsyncSemaphoreTests.swift:173]: nit: we can just write `@Test` instead

File: Tests/SpeziFoundationTests/ManagedAsynchronousAccessTests.swift [hunk 8]
```diff
@@ -6,260 +6,269 @@
...
-            expectation.fulfill()
+            
+            try await Task.sleep(for: .milliseconds(100))
+            
+            #expect(access.ongoingAccess == true)
+            #expect(task.isCancelled == false)
+            
+            access.cancelAll()
+            
+            #expect(access.ongoingAccess == false)
```
Comment (lukaskollmer) [inline Tests/SpeziFoundationTests/ManagedAsynchronousAccessTests.swift:123]: nit (here and in a couple of other places): we should probably remove the `== true` and write `!x` instead of `x == false`.

File: .github/workflows/swift-build-and-test.yml [hunk 9]
```diff
@@ -0,0 +1,85 @@
...
+        type: boolean
+        default: false
+    secrets:
+      CHECKOUT_TOKEN:
+        description: |
+          The Personal access token (PAT) to use with the checkout action.
+        required: false
+
+jobs:
+  linux_build_and_test:
```
Comment (lukaskollmer) [inline .github/workflows/swift-build-and-test.yml:57]: this is still called `linux_build_and_test`, while the file has already been renamed to `swift_build_and_test`

File: Dockerfile [hunk 10]
```diff
@@ -0,0 +1,25 @@
...
+
+RUN swift package resolve
+
+# Build SpeziFoundation & Tests
+RUN swift build  --build-tests -v
+
+
+
+# Run Tests
+RUN swift test --skip-build
```
Comment (lukaskollmer) [inline Dockerfile:23]: what's the benefit in splitting this up into two separate steps?

**Comment by Seb-Ltz** [comment]
@lukaskollmer Sorry for the delay, I completely missed this one. Thanks for the reminder! I'll look into the comments and update the PR today / within the next couple of days.

File: .github/workflows/swift-build-and-test.yml (hunk 9 above)
Comment (Seb-Ltz) [reply .github/workflows/swift-build-and-test.yml:57]: Oh good catch, thank you for that comment!

File: Dockerfile (hunk 10 above)
Comment (Seb-Ltz) [reply Dockerfile:23]: Good point as well, I'll simplify that to just `RUN swift test -v` 👍

File: Tests/SpeziFoundationTests/MainActorExecutionTests.swift [hunk 11]
```diff
@@ -15,17 +15,49 @@ import Testing
 /// Internal helper actor to be able to have code run guaranteed off the main actor (by scheduling it onto a background queue)
 @globalActor
 private actor TestActor: GlobalActor {
+    final class DispatchQueueExecutor: SerialExecutor {
```
Comment (PSchmiedmayer) [inline Tests/SpeziFoundationTests/MainActorExecutionTests.swift:18]: Is this type actually needed here? I might miss something, but if we don't use the tests on Linux, we could stick with the old setup?

File: Sources/SpeziFoundation/Concurrency/RWLock/AtomicPThread.swift [hunk 12]
```diff
@@ -0,0 +1,41 @@
...
+
+import Atomics
+import Foundation
+#if canImport(Glibc)
+import Glibc
+#endif
+
+#if canImport(Darwin)
+typealias AtomicPThread = ManagedAtomic<pthread_t?> // swiftlint:disable:this file_types_order
+#else
```
[the remark this answers is not in the document]
Comment (Seb-Ltz) [reply Sources/SpeziFoundation/Concurrency/RWLock/AtomicPThread.swift:17]:
```swift
import Atomics
import Foundation

#if canImport(Darwin)
typealias AtomicPThread = ManagedAtomic<pthread_t?> // swiftlint:disable:this file_types_order
#elseif canImport(Glibc)
import Glibc

struct AtomicPThread {
    ...
}
#endif
```
Sounds good! Just to be sure, would this be okay like this, to put the `import Glibc` after the Darwin branch?

[the remark this answers is not in the document]
Comment (lukaskollmer) [reply Sources/SpeziFoundation/Concurrency/RWLock/AtomicPThread.swift:17]: yes, that seems like a good approach. i think paul's suggestion would also include an error branch at the end, for the case that neither Darwin nor Glibc are available:
```swift
#if canImport(Darwin)
// do darwin stuff
#elseif canImport(Glibc)
// do Glibc stuff
#else
#error("Unable to import neither Darwin nor Glibc")
#endif
```

tbh i don't think there will exist any platforms where both are missing, but i guess it's nice to easily know why the build is failing in that case

also, feel free to just have a file-level `swiftlint:disable file_types_order` at the beginning of the file (after the license comment) instead of having to annotate every definition individually

**Comment by Seb-Ltz** [comment]
Thanks for the review @PSchmiedmayer @lukaskollmer 🚀

I've implemented your feedback in the latest commit.

**Comment by PSchmiedmayer** [comment]
Thank you @phnagy for continuing to work on this and working on getting the tests in a passing state 👍

File: Tests/SpeziFoundationTests/RWLockTests.swift [hunk 13]
```diff
@@ -77,7 +77,23 @@ final class RWLockTests: XCTestCase {
...
+    //
+    // On Linux (glibc), `pthread_rwlock_trywrlock()` instead returns `EBUSY` in the same
+    // scenario (only `pthread_rwlock_wrlock()` can return `EDEADLK`)
+    //
+    // To make this portable, `RWLock` would need to explicitly track ownership
+    // of the lock by the current thread.
+    //
+    // See
+    // - https://linux.die.net/man/3/pthread_rwlock_trywrlock
+    // - https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/pthread_rwlock_trywrlock.3.html
```
Comment (PSchmiedmayer) [inline Tests/SpeziFoundationTests/RWLockTests.swift]: Should we create an issue for this to address it later on in follow-up works @phnagy?

**Review by PSchmiedmayer — APPROVED** [review]
Happy to see this merge; can you ensure that all conversations are resolved an all remaining issues are moved into follow-up GitHub issues @phnagy? 

Please ping me to merge it after that and we can then move on to the main Spezi package.
